language: php
php:
  - '7.1'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

addons:
  sonarcloud:
    organization: "shoppingfeed"
    token:
      secure: "UxC3EQ9o7eLfX4q2kW+g5WOSN0LtCJQm6s6qav/Af/ht812QTxDMk3eC8pUwwfG+U5GNdNLpavU6IT2+9fEH6Fr4pBJRMvOuFe6P6y7Hgu+QTcN1TmIIlqHigG82PrTK4SPni9HNqvG3sjDPGp6jICF58xnVGNeUM8DgawUqPUSGExyVMwgMEVbIvTighniFOWf7OQVrsRCVLUfxIlhkXFT1aDTAHeYlm/KtcoOiIhAEoBYqC9Og5Wn8esWBlskQYzH+ZfI0pSFTlT62RGERJhCNwyKONyJWomt+jCUM9Nag7mqGZdDYG/J1gwm/oS5yVgkHWntSNOoqByfDfMkatz0CmLr8bcvzVwTAcTsqzOxJ3vlw1ewHTWp7qAQtW6B2/F8MFNuhGXDPJCIdc1FuVKs/6u56Iph/WO1WHA8qPKcgYb/eayvIwkpCVb24dbiTFYFCXXGMJ67LRA+WJTYx0OY2rdZw0fl5tO45PRIrCOoFsqEsSdUmhrAKEEkAgVCNFOWHekIOSczYabl8ISiioObKtgyJj9v31Zt8EXipPsV96X/TdFNHsWIRx2tKranpKOG66e0MpXBgOoK2Bnj7U2PXHteryR+DbBrkICAHmKsO6gQ85aiMBWbwmZOE4qjH60f+4sfFG3bwFI60HJ7Q6allDfmYnRj567gjwTgM9z0="

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=build/clover.xml --log-junit=build/junit.xml
  - sonar-scanner